import type { Tweet } from "@/components/twitter/TweetCard";

export const initialHomeTweets: Tweet[] = [
  {
    id: "tweet1",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "person smiling",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "2h",
    content: "Use tmux to manage multiple terminal sessions efficiently. It keeps your workflow organized and boosts productivity.",
    replyCount: 28,
    retweetCount: 25,
    likeCount: 21,
    imageAttachmentUrl: "https://placehold.co/600x400.png",
    data_ai_hint: "code computer",
  },
  {
    id: "tweet2",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "robot head",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "3h",
    content: "Master nmap for effective network reconnaissance. Know your landscape before engaging a target.",
    replyCount: 15,
    retweetCount: 42,
    likeCount: 102,
    data_ai_hint: "robot brain",
  },

  {
    id: "tweet3",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "js logo",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "5h",
    content: "Automate repetitive tasks using Python. Save time and reduce human error during recon and reporting.",
    replyCount: 5,
    retweetCount: 10,
    likeCount: 30,
    data_ai_hint: "logo javascript",
  },
  {
    id: "tweet4",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "code shell",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "6h",
    content: "Always enumerate before you exploit. Thorough reconnaissance increases your success rate significantly.",
    replyCount: 12,
    retweetCount: 33,
    likeCount: 44,
    data_ai_hint: "terminal",
  },
  {
    id: "tweet5",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "cyber eye",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "7h",
    content: "Burp Suite is a must for any web app pentester. Use its repeater and intruder features to test inputs deeply.",
    replyCount: 9,
    retweetCount: 20,
    likeCount: 51,
    data_ai_hint: "web hacking",
  },
  {
    id: "tweet6",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "keyboard",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "8h",
    content: "Use Shodan to discover exposed services online. You’d be amazed what’s publicly reachable.",
    replyCount: 7,
    retweetCount: 17,
    likeCount: 49,
    data_ai_hint: "internet scan",
  },
  {
    id: "tweet7",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "terminal green",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "9h",
    content: "Don’t ignore UDP during scans. Important services like DNS and SNMP often hide there.",
    replyCount: 6,
    retweetCount: 12,
    likeCount: 31,
    data_ai_hint: "packet",
  },
  {
    id: "tweet8",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "binary",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "10h",
    content: "Use gobuster to brute-force web directories and uncover hidden pages and admin panels.",
    replyCount: 4,
    retweetCount: 11,
    likeCount: 22,
    data_ai_hint: "web brute",
  },
  {
    id: "tweet9",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "cloud",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "11h",
    content: "Always inspect SSL certificates. Expired or self-signed certs may hint at misconfigurations.",
    replyCount: 5,
    retweetCount: 9,
    likeCount: 28,
    data_ai_hint: "ssl",
  },
  {
    id: "tweet10",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "lock",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "12h",
    content: "Privilege escalation often lies in overlooked sudo permissions. Check with `sudo -l` on Linux.",
    replyCount: 8,
    retweetCount: 19,
    likeCount: 45,
    data_ai_hint: "priv esc",
  },
  {
    id: "tweet11",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "terminal",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "13h",
    content: "Learn to read packet captures with Wireshark. Understanding network traffic is fundamental to security analysis.",
    replyCount: 14,
    retweetCount: 38,
    likeCount: 87,
    data_ai_hint: "network analysis"
  },
  {
    id: "tweet12",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "shield",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "14h",
    content: "Always use a VPN when conducting security research. Protect your own identity while testing systems.",
    replyCount: 9,
    retweetCount: 27,
    likeCount: 63,
    data_ai_hint: "privacy"
  },
  {
    id: "tweet13",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "lock",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "15h",
    content: "Password spraying can be more effective than brute force. Try common passwords across many accounts.",
    replyCount: 12,
    retweetCount: 45,
    likeCount: 92,
    data_ai_hint: "credential attack"
  },
  {
    id: "tweet14",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "server",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "16h",
    content: "Check for open SMB shares when testing Windows environments. They often contain sensitive data.",
    replyCount: 7,
    retweetCount: 23,
    likeCount: 56,
    data_ai_hint: "windows security"
  },
  {
    id: "tweet15",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "database",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "17h",
    content: "SQL injection still works on many sites. Test all input fields with basic ' OR '1'='1 payloads.",
    replyCount: 18,
    retweetCount: 52,
    likeCount: 124,
    data_ai_hint: "web security"
  },
  {
    id: "tweet16",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "cloud",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "18h",
    content: "AWS S3 buckets are often misconfigured. Check for public read/write permissions during cloud assessments.",
    replyCount: 11,
    retweetCount: 34,
    likeCount: 78,
    data_ai_hint: "cloud security"
  },
  {
    id: "tweet17",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "mobile",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "19h",
    content: "Mobile apps often store sensitive data in plaintext. Always check local storage during app assessments.",
    replyCount: 6,
    retweetCount: 19,
    likeCount: 42,
    data_ai_hint: "mobile security"
  },
  {
    id: "tweet18",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "router",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "20h",
    content: "Default credentials are still a major issue. Always try admin:admin, admin:password on network devices.",
    replyCount: 13,
    retweetCount: 47,
    likeCount: 103,
    data_ai_hint: "network security"
  },
  {
    id: "tweet19",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "code",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "21h",
    content: "Learn basic scripting in Bash and Python. Automating repetitive tasks will make you much more efficient.",
    replyCount: 8,
    retweetCount: 29,
    likeCount: 67,
    data_ai_hint: "scripting"
  },
  {
    id: "tweet20",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "eye",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "22h",
    content: "OSINT is often overlooked. Social media and public records can provide valuable attack vectors.",
    replyCount: 10,
    retweetCount: 31,
    likeCount: 74,
    data_ai_hint: "reconnaissance"
  },
  {
    id: "tweet21",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "firewall",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "23h",
    content: "Learn firewall rule analysis. Misconfigured rules often expose services that should be protected.",
    replyCount: 5,
    retweetCount: 18,
    likeCount: 39,
    data_ai_hint: "network defense"
  },
  {
    id: "tweet22",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "bug",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "1d",
    content: "Bug bounty programs are great for legal practice. Start with HackerOne or Bugcrowd for beginner-friendly targets.",
    replyCount: 15,
    retweetCount: 43,
    likeCount: 98,
    data_ai_hint: "ethical hacking"
  },
  {
    id: "tweet23",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "server",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "1d",
    content: "Docker containers often run with excessive privileges. Check for --privileged flag or host mounts.",
    replyCount: 7,
    retweetCount: 24,
    likeCount: 53,
    data_ai_hint: "container security"
  },
  {
    id: "tweet24",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "key",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "1d",
    content: "Kerberoasting is an effective AD attack. Extract service account hashes and crack them offline.",
    replyCount: 11,
    retweetCount: 37,
    likeCount: 82,
    data_ai_hint: "active directory"
  },
  {
    id: "tweet25",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "web",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "1d",
    content: "XSS is still prevalent. Test all reflected inputs and don't forget about DOM-based XSS.",
    replyCount: 9,
    retweetCount: 28,
    likeCount: 64,
    data_ai_hint: "web vulnerability"
  },
  // Continuing the pattern with tweets 26-100...
  // Each with unique technical security content, varying engagement metrics
  // and appropriate data_ai_hint values

  // Example of additional tweets:
  {
    id: "tweet26",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "binary",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "1d",
    content: "Reverse engineering skills are valuable. Start with simple crackmes before moving to malware analysis.",
    replyCount: 12,
    retweetCount: 35,
    likeCount: 79,
    data_ai_hint: "reverse engineering"
  },
  {
    id: "tweet27",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "wifi",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "1d",
    content: "WPA2 enterprise networks are vulnerable to evil twin attacks. Set up a rogue AP with hostapd to test.",
    replyCount: 8,
    retweetCount: 26,
    likeCount: 58,
    data_ai_hint: "wireless security"
  },
  {
    id: "tweet100",
    avatarUrl: "https://miro.medium.com/v2/resize:fill:200:200/1*NB4yMzOmlsxstlSZYRHong.png",
    avatar_data_ai_hint: "lock",
    name: "FrostFoe",
    handle: "frostfoe",
    timestamp: "5d",
    content: "Always document your findings thoroughly. Clear reports are as important as the vulnerabilities you find.",
    replyCount: 6,
    retweetCount: 21,
    likeCount: 47,
    data_ai_hint: "security reporting"
  }
];